### ISSUE TITLE
api-0.1.0.0 does not compile

### ISSUE THREAD

**Issue by peti** [klappvisor/haskell-telegram-api#1]
Citing from http://hydra.cryp.to/build/1502152/log/raw:

~~~~~
Building telegram-api-0.1.0.0...
Preprocessing library telegram-api-0.1.0.0...

src/Web/Telegram/API/Bot/Data.hs:36:18:
    Could not find module ‘Web.Telegram.API.Bot.JsonExt’
    Use -v to see a list of the files searched for.
~~~~~

**Comment by klappvisor** [comment]
Hi Peter,

Looks pretty strange... I will take a look once I have time

**Comment by klappvisor** [comment]
According to http://hydra.cryp.to/build/1522221/log newer version of telegram-api-0.1.0.1 compiles successfully, but fails on test step.

Right now tests are written to be run against real Telegram Bot API and requires bot's token and user chat_id to be passed in.

https://circleci.com/gh/klappvisor/haskell-telegram-api

**Comment by peti** [comment]
Oh, okay. In that case, we cannot execute the test suite because Nix builds these packages in an isolated `chroot()` sandbox that doesn't have network access.

**Comment by klappvisor** [comment]
By default tests are disabled now, hydra build successful.
