### ISSUE TITLE
Support for servant 0.11?

### ISSUE THREAD

**Issue by peti** [klappvisor/haskell-telegram-api#100]
Is there going to be an update that adds support for recent versions of servant?

**Comment by cevantes** [comment]
the package didn't make it to lts-9.0 because of servant breaking update

**Comment by klappvisor** [comment]
Sorry for that big break in maintaining this package. migrated to servant-0.11

**Comment by cevantes** [comment]
Although it's about time to start worrying about servant-0.12 :)

**Comment by klappvisor** [comment]
oh yeah, seems to be a big change
