### ISSUE TITLE
Documentation request: Step-by-step instructions on how to execute the tests

### ISSUE THREAD

**Issue by timjb** [klappvisor/haskell-telegram-api#11]
I've created a bot by contacting the Botfather. Now what? Where can I get a suitable `chat_id`?

**Comment by klappvisor** [comment]
@timjb I don't remember exactly how and where, but you can use Bot API and REST client to get it. Try  to write a message into bot's chat and call getUpdates. I believe it will be there

**Comment by klappvisor** [comment]
I'm going to update documentation tonight

**Comment by timjb** [comment]
Thanks!
