### ISSUE TITLE
Test "should send photo" fails when executed locally

### ISSUE THREAD

**Issue by timjb** [klappvisor/haskell-telegram-api#27]
My guess is that the hardcoded `file_id` in the test source code only works with @klappvisor's test bot.

**Comment by klappvisor** [comment]
confirmed

**Comment by klappvisor** [comment]
@timjb I have tried to redirect the photo to public channel to make it available. Could you please check is it still failing?

**Comment by timjb** [comment]
It's still failing. Here's the response from `sendPhoto`:

    Left (FailureResponse {responseStatus = Status {statusCode = 400, statusMessage = "Bad Request"}, responseContentType = application/json, responseBody = "{\"ok\":false,\"error_code\":400,\"description\":\"Wrong file identifier was specified\"}"})

**Comment by klappvisor** [comment]
@ hopefully #33 will fix it. (When you redirect photo to public chat, Telegram assigns new id to it)

**Comment by timjb** [comment]
No, #33 didn't fix the tests for me. Now (with 759b647a4ecfeb44af452a937ebbaee1f7406452), I'm getting two failures:

>    should send photo with file_id FAILED [1]
>    ...
>    should send audio FAILED [2]

**Comment by klappvisor** [comment]
well... at least it works for CI. I'll keep issue open

**Comment by klappvisor** [comment]
should be fixed for images, since now tests upload image first and then send it again by id

**Comment by klappvisor** [comment]
Changed audio test to follow the same logic as the test for photos, so now it should be fixed. Please reopen this issue, it it's still failing
