### ISSUE TITLE
Add to stackage

### ISSUE THREAD

**Issue by Arguggi** [klappvisor/haskell-telegram-api#49]
The package seems to build fine with the lastest `lts` and `nightly` from `stackage`, so maybe you could try and add it by sending a PR to the [stackage repo?](https://github.com/fpco/stackage)

I'm not sure if more specific versions for dependencies in the `cabal` file are needed or recommended though.

**Comment by klappvisor** [comment]
Thanks for idea. Created [PR](https://github.com/fpco/stackage/pull/1473). let's see

**Comment by Arguggi** [comment]
Seems like they merged the PR :+1:

**Comment by klappvisor** [comment]
@Arguggi Thank you for contibution!
