### ISSUE TITLE
inlineKeyboardMarkup for SendMessageRequest

### ISSUE THREAD

**Issue by hcvst** [klappvisor/haskell-telegram-api#55]
Hi Klappvisor,

thank you for very much your package. 

I noticed that I cannot specify `inlineKeyboardMarkup` for ordinary `SendMessageRequest` messages, which the Telegram API supports though. 

I am just porting a nodejs bot to your haskell-telegram-api to get my hands dirty with Haskell. I am not confident enough yet to send you a pull request.

Best regards,
HC

**Comment by klappvisor** [comment]
Hi HC,

Check out MR #53 I think it's exactly what you want. MR was merged yesterday and version 0.4.3.0 was released. telegram-api v0.4.3.0 is not in LTSHaskell yet, but it's available in Stackage ([link](https://www.stackage.org/package/telegram-api)).

Good luck with Haskell!

Regards,
klappvisor

**Comment by hcvst** [comment]
Ah, good. Thank you, klappvisor.

**Comment by klappvisor** [comment]
I am going to close it, but if you still have issue, you can reopen it
