### ISSUE TITLE
Build failing:

### ISSUE THREAD

**Issue by jgalat0** [klappvisor/haskell-telegram-api#7]
[5 of 6] Compiling Web.Telegram.API.Bot.API ( src/Web/Telegram/API/Bot/API.hs, dist/build/Web/Telegram/API/Bot/API.o )

src/Web/Telegram/API/Bot/API.hs:53:10:
    Not in scope: type constructor or class `ToText'
    Perhaps you meant `Text' (imported from Data.Text)

src/Web/Telegram/API/Bot/API.hs:56:10:
    Not in scope: type constructor or class `FromText'
cabal: Error: some packages failed to install:
telegram-api-0.2.1.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by klappvisor** [comment]
Referring to status of [CI build](https://circleci.com/gh/klappvisor/haskell-telegram-api/28) it is passing.
Could you please provide more information about you environment besides just output from build task?

**Comment by jgalat0** [comment]
(Sorry for bad english and not explaining before)
Just used
 `cabal install telegram-api`
It installed all dependencies listed in [hackage](https://hackage.haskell.org/package/telegram-api). But when it comes to building telegram-api, it prints this error. I believe you are using this classes http://haskell-servant.github.io/servant/Servant-Common-Text.html, could it be? And somehow it is not finding them

**Comment by jgalat0** [comment]
I believe i've found the error (or may not...):
I found this line from the Changelog of servant-client, 
`Use http-api-data instead of Servant.Common.Text`
https://github.com/haskell-servant/servant/blob/master/servant-client/CHANGELOG.md

**Comment by klappvisor** [comment]
OK. I will trigger rebuild to check dependencies. But at the same time I would advise you to start using stack to build you haskell projects. It's a nice tool

**Comment by klappvisor** [comment]
migrated to latest servant and added version number for servant dependencies. if issue still exists feel free to reopen it
