### ISSUE TITLE
Add "allowed_updates" parameter to `getUpdates` method

### ISSUE THREAD

**Issue by Vdimir** [klappvisor/haskell-telegram-api#74]
According documentation to [getUpdates](https://core.telegram.org/bots/api#getupdates) there is way to filter types of received updates. But I have not found way to use this feature through this bindings.

**Comment by klappvisor** [comment]
`getUpdatesM` is available now in latest 0.6.0.0 release. you can specify `updates_allowed_updates` field in `GetUpdatesRequest`
