### ISSUE TITLE
Unique identifier of chat may be greater than 32 bits

### ISSUE THREAD

**Issue by yurael** [klappvisor/haskell-telegram-api#87]
Just for clear.
According to [Telegram Bot API](https://core.telegram.org/bots/api#chat) the definition of Chat id says that number may be greater 32 bits and smaller 52 bits. But `chat_id` defined as `Int`. Is that an issue?

**Comment by klappvisor** [comment]
Actually you are right, I'm going to fix this soon

**Comment by klappvisor** [comment]
kudos to @cblp
